version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python manage.py runserver"
    ports:
      - "8000:8000"
    working_dir: /usr/src/app
    env_file:
      - .env
    depends_on:
      - worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: "rq worker --url=${REDIS_URL}"
    working_dir: /usr/src/app
    env_file:
      - .env
      