# WARNING

# REQUIRING OR EXECUTING THIS SCRIPT WILL DELETE ALL THE KEYS FROM REDIS
# THIS IS FOR TEST CASES ONLY

from Redis import _redis
from Pairs import SUPPORTED_PAIRS

for pair in SUPPORTED_PAIRS:
  _redis.delete(SUPPORTED_PAIRS[pair]['redisKey'])

# REQUIRING OR EXECUTING THIS SCRIPT WILL DELETE ALL THE KEYS FROM REDIS
# REQUIRING OR EXECUTING THIS SCRIPT WILL DELETE ALL THE KEYS FROM REDIS
# REQUIRING OR EXECUTING THIS SCRIPT WILL DELETE ALL THE KEYS FROM REDIS